apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: chat-app
spec:
  selector:
    app: backend
  ports: 
   - protocol: TCP
     port: 5001
     targetPort: 5001
  type: ClusterIP
